version: '3.7'

services:

  ops-scripts:
    container_name: ops-scripts
    image: marcelndeffo/tools:ops-scripts-local
    build: .
    restart: no
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: $PWD/tests/data/audio  # Replace here with your source directory
        target: /data/audio
