FROM python:3.10-alpine as base

ENV DVC_VERSION="3.7.0"
ENV LIBGIT2_VERSION="1.7.1"

RUN apk update

RUN apk add jq git bash

FROM base as pre-build

RUN apk add --update --no-cache gcc python3-dev py-pip musl-dev linux-headers cmake make

RUN apk add --update --no-cache openssl-dev libffi-dev

#compile libgit2
RUN ( git clone https://github.com/libgit2/libgit2.git &&  \
      cd libgit2 && git checkout tags/v$LIBGIT2_VERSION && \
      mkdir build && cd build/ && \
      cmake .. -DCMAKE_INSTALL_PREFIX=/usr && \
      cmake --build . --target install )

RUN python3 -m venv /venv
ENV PATH=/venv/bin:$PATH

# Install dvc
RUN python3 -m pip install dvc==$DVC_VERSION

FROM base

#copying python binaries
COPY --from=pre-build /venv /venv
ENV PATH=/venv/bin:$PATH

RUN dvc --version

ENTRYPOINT '/bin/sh'
