FROM alpine:edge as base

RUN apk update

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

FROM base as pre-build

RUN apk add --update --no-cache gcc python3-dev musl-dev libgit2-dev linux-headers
RUN python3 -m venv /venv
ENV PATH=/venv/bin:$PATH

# Install dvc
RUN pip install dvc

FROM base

RUN apk add jq git bash

#copying python binaries
COPY --from=pre-build /venv /venv
ENV PATH=/venv/bin:$PATH

RUN dvc --version

ENTRYPOINT '/bin/sh'
