FROM alpine:3.18 as base

ENV METRICS_EXPORTER_VERSION=1.6.1

WORKDIR /build

RUN apk add wget

RUN (wget https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-$METRICS_EXPORTER_VERSION.linux-amd64.tar.gz && \
    tar xvfz node_exporter-$METRICS_EXPORTER_VERSION.linux-amd64.tar.gz && \
    rm node_exporter-$METRICS_EXPORTER_VERSION.linux-amd64.tar.gz && \
    mv node_exporter-$METRICS_EXPORTER_VERSION.linux-amd64 metrics )

FROM alpine:3.18

EXPOSE 9100

COPY --from=base /build/metrics/node_exporter /usr/bin/metrics

CMD metrics





