#!/usr/bin/env bash

function usage() {
    echo -e \
"Usage:
  bash compute-audio-space/run -s source_directory -m method
  compute non-variant space from audio files in the source directory.
  Arguments:
   - s: target directory
   - m: compute method [expensive/direct/fractal] :: default=='default'
   - l: fractal level for the recursive chopping :: default=='3'
  "
}


ROOT_DIR=$(dirname "$0")

#Load source(s)
source "$ROOT_DIR/shared/utils.sh"
source "$ROOT_DIR/shared/preprocess.sh"
source "$ROOT_DIR/shared/compute.sh"

#Load arguments
source "$ROOT_DIR/shared/args.sh"

#Dependencies check
dependencies

#preprocess audio files
preprocess

#Compute FFT of original / reverted / palindromic audio file
[[ "$COMPUTE_METHOD" == @("expensive"|"default") ]] && compute-p

#Compute FFT of original / chop #1 / chop #2
[[ "$COMPUTE_METHOD" == "fractal" ]] && compute-f

if [[ "$COMPUTE_METHOD" == @("expensive"|"fractal") ]]; then { cd "$SOURCE_DIRECTORY" && wipe-chops; }; fi


