FROM alpine:edge as base

RUN apk update

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN python --version

# Install ffmpeg
RUN apk add ffmpeg
RUN ffmpeg -version

ENTRYPOINT '/bin/sh'