FROM alpine:edge as base

RUN apk update

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 py-pip
RUN python3 --version

# Install ffmpeg
RUN apk add ffmpeg bash
RUN ffmpeg -version

ENTRYPOINT '/bin/sh'