FROM alpine:latest

RUN apk update

# ci utilitaries
RUN apk add --update --no-cache make jq

# Install python/pip and utilitaries
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 py-pip
RUN ln -sf /usr/bin/python3 /usr/bin/python

RUN python --version

# ci python utilitary
RUN pip install poetry

# Install ffmpeg
RUN apk add ffmpeg bash
RUN ffmpeg -version

ENTRYPOINT '/bin/sh'