version: '3.3'

services:

  upstride:
    restart: always
# Change here >>>>>> 
    container_name: upstride-client
    image: tensorflow/tensorflow:latest-gpu
    command: python -c "import tensorflow as tf;tf.test.gpu_device_name()"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
# <<<<<<
    networks:
      upstride_vnet:
        ipv4_address: 172.16.0.2
    logging:
      driver: fluentd
      options:
        tag: "docker.prod.onprem.{{.Name}}"
        fluentd-address: "tcp://0.0.0.0:24230"
        mode: non-blocking
        max-buffer-size: 10m
    depends_on:
      - monitoring-agent

  monitoring-agent:
    restart: always
    image: registry.us.upstride.io/ops/monitoring/image:agent-1.0.0
    container_name: monitoring-agent
    logging:
      options:
        max-size: "5m"
        max-file: "5"
    ports:
      - "24230:24225"
      - "24230:24225/udp"
    networks:
      upstride_vnet:
        ipv4_address: 172.16.0.3

networks:
  upstride_vnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
