FROM ubuntu:22.04 AS base-python

ARG VERSION="3.11"

ENV TZ=US/Pacific
ENV DEBIAN_FRONTEND=noninteractive

# As root
USER root

# Update the apt repo
RUN apt-get update

# Install Python
RUN apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get install -y python${VERSION} python${VERSION}-dev \
    python3-pip

# Upgrade packages to the latest version
RUN apt-get -y upgrade

# Update PIP (Python's package manager)
RUN python3 -m pip install --upgrade pip

# Set VERSION as the default Python interpreter
RUN update-alternatives --install /usr/bin/python3 python /usr/bin/python${VERSION} 1
RUN update-alternatives --set python /usr/bin/python${VERSION}
RUN update-alternatives --set python /usr/bin/python${VERSION}
RUN ln -s /usr/bin/python${VERSION} /usr/bin/python

# Test python
RUN python3 --version
RUN python --version

FROM base-python AS user-python

ARG TESSELITE_USER=tesselite

# Install network tools
RUN apt-get -y install curl dnsutils

# Install git
RUN apt-get -y install git-all

# Install terminal
RUN apt-get -y install ttyd

# User setup

RUN adduser $TESSELITE_USER  --disabled-password

USER $TESSELITE_USER:$TESSELITE_USER

WORKDIR /home/$TESSELITE_USER

# Install jupyter
RUN python -m pip install jupyterlab

# Position Env
ENV PATH=/home/$TESSELITE_USER/.local/bin/:$PATH

ENV PYTHONPATH=/home/$TESSELITE_USER

# Entry command
CMD ["python", "-m", "jupyter", "lab", "--port", "8001"]




