FROM ubuntu:22.04

ARG VERSION="3.11"

ENV TZ=US/Pacific
ENV DEBIAN_FRONTEND=noninteractive

# As root
USER root

# Update the apt repo
RUN apt-get update

# Install Python
RUN apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get install -y python${VERSION} python${VERSION}-dev \
    python3-pip

# Install git
RUN apt-get -y install git-all

# Install terminal
RUN apt-get -y install ttyd

# Install pupyterlab
RUN pip install jupyterlab

# Upgrade packages to the latest version
RUN apt-get -y upgrade

# Update PIP (Python's package manager)
RUN python3 -m pip install --upgrade pip

# Set VERSION as the default Python interpreter
RUN update-alternatives --install /usr/bin/python3 python /usr/bin/python${VERSION} 1
RUN update-alternatives --set python /usr/bin/python${VERSION}
RUN update-alternatives --set python /usr/bin/python${VERSION}
RUN ln -s /usr/bin/python${VERSION} /usr/bin/python

# Test python
RUN python3 --version
RUN python --version

# purge caches
RUN apt-get clean
RUN python -m pip cache purge

# As user
CMD jupyter lab




