version: '3.3'

services:

  upstride:
    restart: always
# Change here >>>>>> 
    container_name: upstride-client
    image: tensorflow/tensorflow:latest-gpu
    command: python -c "import tensorflow as tf;tf.test.gpu_device_name()"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
# <<<<<<
    networks:
      upstride_vnet:
        ipv4_address: 172.16.0.2
    logging:
      driver: fluentd
      options:
        tag: "docker.uat.{{.Name}}"
        fluentd-address: "tcp://0.0.0.0:24230"
    depends_on:
      - monitoring-agent

  monitoring-agent:
    image: registryupstrideprod.azurecr.io/ops/monitoring/image:agent-1.0.2
    container_name: monitoring-agent
    ports:
      - "24230:24225"
      - "24230:24225/udp"
    networks:
      upstride_vnet:
        ipv4_address: 172.16.0.3

networks:
  upstride_vnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
