FROM ubuntu:latest

RUN ( apt update &&  apt install -y git pre-commit jq wget )


RUN ( wget https://dvc.org/deb/dvc.list -O /etc/apt/sources.list.d/dvc.list && \
        wget -qO - https://dvc.org/deb/iterative.asc | gpg --dearmor > packages.iterative.gpg && \
        install -o root -g root -m 644 packages.iterative.gpg /etc/apt/trusted.gpg.d/ && \
        rm -f packages.iterative.gpg && \
        apt update && \
        apt -y install dvc )

RUN apt autoclean

ENTRYPOINT '/bin/sh'
