#!/usr/bin/env bash

function usage() {
    echo -e \
"Usage:
  bash browse-github/run -o facebook
  browse organization's github and extract information on repos.
  Arguments:
   - o: organization name.
   - d: debug mode
  "
}

ROOT_DIR="$(dirname "$0")"

source "$ROOT_DIR/shared/args.sh"
source "$ROOT_DIR/../transform-av/shared/utils.sh"

function info() {
  [ -n "$VERBOSE" ] && echo -e "$1" >&2 || return 0
}

#Dependencies check
info "+ dependencies checks"
dependencies_print

#Call python scripts
info "+ list github repos"
$PYTHON_BIN "$ROOT_DIR/shared/scripts.py" list --org "$ORGANIZATION_NAME"
