#!/usr/bin/env bash

function usage() {
    echo -e \
"Usage:
  bash transform-av/chop/run -s source_directory -l N
  chop audio files '.wav' to smaller files N times.
  Arguments:
   - s: target directory
   - l: level of chop
  "
}

ROOT_DIR=$(dirname "$0")

#Load source(s)
source "$ROOT_DIR/../shared/utils.sh"
source "$ROOT_DIR/../shared/preprocess.sh"
source "$ROOT_DIR/args.sh"
SOURCE_DIRECTORY=$(realpath "$SOURCE_DIRECTORY")

#Overload compute functions
function pre() {
  debug "+ into 'pre'"
  [ -d "$SOURCE_DIRECTORY/.chopped/" ] && { debug "-- clearing '.chopped' directory"; rm -r "$SOURCE_DIRECTORY/.chopped/"; }
  mkdir "$SOURCE_DIRECTORY/.chopped/"
  cd "$directory" && wipe-chops || true
  debug "+ exit 'pre'"
}

function post() {
  old_chops=$(find "$SOURCE_DIRECTORY" -iname '*.y.wav')
  if [ -n "${old_chops[*]}" ]; then
    [ "$MOVE_CHOPS" == "yes" -a "$FRACTAL_LEVEL" -gt 0 ] && mv "$SOURCE_DIRECTORY"/*.y.wav "$SOURCE_DIRECTORY/.chopped/"|| true
  fi
  info "+ alright!"
}

function compute() {
  file=$1
  debug "+ original: $file"
  for i in $(seq 1 "$FRACTAL_LEVEL"); do
    chop "$(for ((j=$((i-1)); j<="$i"; j++)); do echo "${file//.wav/$(yy "$j").wav}"; done)" || exit 2
  done
}

#Dependencies check
dependencies

#Loop
loop '*.wav'