name: Build Python Dev

on:
  schedule:
    - cron: '0 7 * * 0'
  push:
    paths:
      - .build/rabbitmq/**
      - .github/workflows/build-pythondev.yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {os: "ubuntu",  tag: "pythondev"}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:.build/pythondev/${{ matrix.os }}"
        push: true
        build-args: |
          VERSION: 3.11
        tags: marcelndeffo/tesselite:${{ matrix.tag }}
