name: Build Prom Docker

on:
  schedule:
    - cron: '0 7 * * 0'
  push:
    paths:
      - .build/prom/**
      - .github/workflows/build-prom.yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {os: "alpine",  tag: "metrics"}
          - {os: "ubuntu",  tag: "ubuntu-metrics"}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:.build/prom/${{ matrix.os }}"
        push: true
        tags: marcelndeffo/tools:${{ matrix.tag }}
