# This workflow will install Python dependencies, run test_blockchain and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Bash Scripts Docker

on:
  push:
    branches: [ main ]
    paths-ignore:
      - .build/
      - .github/workflows/build-*
  pull_request:
    branches: [ main ]
    paths-ignore:
      - .build/
      - .github/workflows/build-*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Only on PR
      id: docker_build
      uses: docker/build-push-action@v3
      if: ${{ github.ref != 'refs/heads/main' }}
      with:
        push: true
        tags: marcelndeffo/tools:ops-scripts-${{ github.sha }}
    - name: Build Only on Main
      id: docker_build_push
      uses: docker/build-push-action@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        push: true
        tags: marcelndeffo/tools:ops-scripts

  test-scrap:
    needs: build
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: marcelndeffo/tools:ops-scripts-${{ github.sha }}
      env:
        VERBOSE: "TRUE"
    steps:
      - name: Run Test Suite
        id: test_docker
        run: |
          /src/tests/run scrap*

  test-compute-1:
    needs: build
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: marcelndeffo/tools:ops-scripts-${{ github.sha }}
      env:
        VERBOSE: "TRUE"
    steps:
      - name: Computation Tests
        id: test_docker
        run: |
          /src/tests/run *compute.sh

  test-compute-2:
    needs: build
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: marcelndeffo/tools:ops-scripts-${{ github.sha }}
      env:
        VERBOSE: "TRUE"
    steps:
      - name: Computation Tests (2)
        id: test_docker
        run: |
          /src/tests/run *compute-2.sh

  test-av:
    needs: build
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: marcelndeffo/tools:ops-scripts-${{ github.sha }}
      env:
        VERBOSE: "TRUE"
    steps:
      - name: Transform Tests
        id: test_docker
        run: |
          /src/tests/run av-transform*