# This workflow will install Python dependencies, run test_blockchain and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Docker

on:
  push:
    branches-ignore:
      - main
    paths:
      - dockerfile
      - requirements.txt
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Only on PR
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: marcelndeffo/tools:skynet
