# This workflow will install Python dependencies, run test_blockchain and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches-ignore:
      - main
    paths:
      - transform-av/**
      - browse-github/**
      - download-yt
      - tests/**
      - .github/workflows/ci.yml

jobs:
  test-scrap:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: marcelndeffo/tools:ops-scripts
      env:
        VERBOSE: "TRUE"
    steps:
      - name: Run Test Suite
        id: test_docker
        run: |
          /src/tests/run scrap*

  test-compute-1:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: marcelndeffo/tools:ops-scripts
      env:
        VERBOSE: "TRUE"
    steps:
      - name: Computation Tests
        id: test_docker
        run: |
          /src/tests/run *compute.sh

  test-compute-2:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: marcelndeffo/tools:ops-scripts
      env:
        VERBOSE: "TRUE"
    steps:
      - name: Computation Tests (2)
        id: test_docker
        run: |
          /src/tests/run *compute-2.sh

  test-av:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: marcelndeffo/tools:ops-scripts
      env:
        VERBOSE: "TRUE"
    steps:
      - name: Transform Tests
        id: test_docker
        run: |
          /src/tests/run av-transform*