#!/usr/bin/env bash

function usage() {
    echo -e \
"Usage:
  bash transform-av/interpolate/run -s source_directory -l N -m interpolation_method
  interpolate audio(s) to new duration N times than duration of the original sample.
  Arguments:
   - s: target directory
   - l: multiply factor
   - m: interpolation method [zeros/linear]
  "
}


ROOT_DIR=$(realpath "$(dirname "$0")/..")

#Load source(s)
source "$ROOT_DIR/shared/utils.sh"
source "$ROOT_DIR/shared/preprocess.sh"

#Load arguments
source "$ROOT_DIR/interpolate/args.sh"

#Overload compute functions
function pre() {
  directory=$(realpath "$SOURCE_DIRECTORY")
  [ -d "$directory/.interpolated/" ] && { debug "-- clearing '.interpolated' directory"; rm -r "$directory/.interpolated/"; }
  mkdir "$directory/.interpolated/"
}

function post() {
  info "+ alright!"
}

function compute() {
  file=$1
  $PYTHON_BIN "$ROOT_DIR/shared/scripts.py" int -a "$file" \
      -o ".interpolated/${file//.wav/$(xx "$((MULTIPLY_FACTOR/2))").wav}" -m "$INT_METHOD"\
      -f "$MULTIPLY_FACTOR" || error "Cannot interpolate '$file'"
}


#Dependencies check
dependencies
dependencies_compute

#Main loop
loop '*.wav'

